name: DocSearch Crawler

on:
  schedule:
    - cron: "0 0 * * *" # It runs once a day, every day at 12:00AM UTC
  push:
    branches:
      - main

jobs:
  docsearch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm ci

    - name: Run DocSearch Crawler
      run: npx docsearch
      env:
        ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
        ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
        ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
        DOCSEARCH_CONFIG_URL: ${{ secrets.DOCSEARCH_CONFIG_URL }}
